GUS_book/Models/Library/Book.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace GUS_book.Models.Library
{
    public class Book
    {
        [Key]
        [Required]
        [DisplayName("Идентификатор")]
        public int Id { get; set; }

        [Required]
        [StringLength(40, ErrorMessage = "Название книги не может содержать больше 40 символов")]
        [DisplayName("Название")]
        public string Title { get; set; }

        [StringLength(20, ErrorMessage = "Имя автора не может содержать больше 20 символов")]
        [DisplayName("Автор")]
        public string  Author { get; set; }

        [Required]
        [DisplayName("Год издания")]
        public int Year { get; set; }

        [HiddenInput(DisplayValue = false)]
        [DefaultValue(0)]
        public int? OwnerId { get; set; } = 0;
    }
}

GUS_book/Models/Library/User.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GUS_book.Models.Library
{
    public class User
    {
        [HiddenInput(DisplayValue = false)]       
        public int Id { get; set; }

        [Required]
        [DisplayName("Имя пользователя")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Возраст")]
        public int Age { get; set; }

        [DataType(DataType.EmailAddress)]
        [DisplayName("Электронная почта")]
        public string Email { get; set; }

        //[Required]
        //[DataType(DataType.Password)]
        //public string Password { get; set; }
    }
}

GUS_book/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using GUS_book.Models;
using GUS_book.Models.Context;
using GUS_book.Models.Library;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace GUS_book.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILogger<LibraryController> _logger;
        private readonly LibraryContext database;

        public LibraryController(ILogger<LibraryController> logger, LibraryContext context)
        {
            _logger = logger;
            this.database = context;
        }

        #region Default actions
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion

        [HttpGet]
        public async Task<IActionResult> Users()
        {
            List<User> users = await database.Users.ToListAsync();
            if (users != null)
                return View(users);
            else
                return RedirectToAction("Error");
        }

        [HttpGet]
        public async Task<IActionResult> Books()
        {
            List<Book> books = await database.Books.ToListAsync();
            if (books != null)
                return View(books);
            else
                return RedirectToAction("Error");
        }

        [HttpGet("{controller}/Books/{action}")]
        [ActionName("Create")]
        public IActionResult CreateBook()
        {
            return View("CreateBook");
        }

        [HttpPost("{controller}/Books/{action}")]
        [ActionName("Create")]
        public async Task<IActionResult> CreateBook(Book book)
        {
            if (!ModelState.IsValid)
                return View("CreateBook");

            bool isMatch = await database.Books.AnyAsync(elem => elem.Title.ToLower() == book.Title.ToLower() && elem.Author.ToLower() == book.Author.ToLower());
            if (isMatch)
            {
                ModelState.AddModelError(string.Empty, "Данная книга уже существует");
                return View("CreateBook");
            }

            database.Books.Add(book);
            await database.SaveChangesAsync();

            return RedirectToAction("Books");
        }

        [HttpGet("/Users/{action}/{id?}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ModelState.AddModelError(String.Empty, "Пустой идентификатор пользователя");
                return RedirectToAction("Error");
            }
            User user = await database.Users.FindAsync(id);

            if (user == null)
            {
                ModelState.AddModelError(String.Empty, "Пользователь не найден");
                return RedirectToAction("Error");
            }


            IEnumerable<Book> userBooks = await database.Books.Where(book => book.OwnerId == user.Id).ToListAsync();
            DetailsUserViewModel viewModel = new DetailsUserViewModel(user.Id, user.Name, userBooks);           
            if (TempData["BookList_Errors"] != null)
            {
                foreach (var item in (TempData["BookList_Errors"] as IEnumerable<object>))
                {
                    ModelState.AddModelError(String.Empty, item.ToString());
                }
                TempData["BookList_Errors_old"] = true;
            }

            return View(viewModel);
        }

        [HttpGet("{controller}/BookList/{id?}")]
        public async Task<IActionResult> BookList(int? Id, int? Mb)
        {
            List<Book> books = await database.Books.Where(book => book.OwnerId == 0 || book.OwnerId == null).ToListAsync();
            int UserId = Id??0;
            int MaxBooks = Mb??4;

            if (books.Count == 0)
                return Content("<p>Свободные книги отсутствуют</p>");

            List<BookSelectViewModel> booksForSelection = GetBooksForViewModel(books, UserId);
            UserBookListViewModel ListForDisplay = new UserBookListViewModel(booksForSelection, MaxBooks);
            return PartialView(ListForDisplay);
        }


        [HttpPost]
        public async Task<IActionResult> BookList(UserBookListViewModel model)
        {
            model.MaxBooks += model.BooksForSelection.Count;
            if (!TryValidateModel(model))
            {
                ModelState.AddModelError(String.Empty, "Ошибка создания списка книг или превышено максимальное число книг для данного пользователя");
                TempData["BookList_Errors"] = (from item in ModelState.Root.Errors select item.ErrorMessage).ToList();
                return RedirectToAction("Details", new {Id = model.BooksForSelection[0].OwnerId });
            }
            else
            {
                TempData.Remove("BookList_Errors");
            }

            List<Book> books = new List<Book>(model.BooksForSelection.FindAll(elem => elem.IsSelected == true));
            database.UpdateRange(books);
            await database.SaveChangesAsync();
            return RedirectToAction("Users");
        }
        private List<BookSelectViewModel> GetBooksForViewModel(List<Book> books, int? UserId)
        {
            List<BookSelectViewModel> listForView = new List<BookSelectViewModel>();

            Parallel.ForEach<Book, List<BookSelectViewModel>>((books), new ParallelOptions {MaxDegreeOfParallelism = 2 }, () =>
            {
                return new List<BookSelectViewModel>();
            },

            (localItem, options, localList) =>
            {
                localList.Add(new BookSelectViewModel(localItem, UserId));               

                return localList;
            },

            (results) =>
            {
                lock(listForView)
                    listForView.AddRange(results);
            });

            return listForView;
        }

    }
}

GUS_book/Views/Library/BookList.cshtml
@model GUS_book.Models.UserBookListViewModel

@using(@Html.BeginForm("BookList", "Library", FormMethod.Post))
{
    @Html.HiddenFor(model => model.MaxBooks)
        <table class="table form-group">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.BooksForSelection[0].IsSelected)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BooksForSelection[0].Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BooksForSelection[0].Author)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BooksForSelection[0].Year)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i< Model.BooksForSelection.Count; i++)
                {
                    <tr>
                        @Html.HiddenFor(modelItem => Model.BooksForSelection[i].Id)
                        <td>
                            @Html.EditorFor(modelItem => Model.BooksForSelection[i].IsSelected)
                        </td>
                        <td>
                            @Html.TextBoxFor(modelItem => Model.BooksForSelection[i].Title, null, new { @readonly = "readonly" })
                        </td>
                        <td>
                            @Html.TextBoxFor(modelItem => Model.BooksForSelection[i].Author, null, new { @readonly = "readonly" })
                        </td>
                        <td>
                            @Html.TextBoxFor(modelItem => Model.BooksForSelection[i].Year, null, new { @readonly = "readonly" })
                        </td>
                        <td>
                            @Html.HiddenFor(modelItem => Model.BooksForSelection[i].OwnerId )
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <input class="form-group" type="submit" value="Отправить" name="sendBooks" />   
}

GUS_book/Views/Library/Books.cshtml
@model IEnumerable<GUS_book.Models.Library.Book>

@{
    ViewData["Title"] = "Книги";
}

<h1>Список книг</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <th>
                @Html.HiddenFor(modelItem => item.OwnerId)
            </th>
        </tr>
}
    </tbody>
</table>
<p>
    <a asp-action="Create">Добавить новую книгу</a>
</p>

GUS_book/Views/Library/CreateBook.cshtml
@model GUS_book.Models.Library.Book

<h1>Новая книга</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="OwnerId" class="form-control" />
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Books">К списку книг</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GUS_book/Views/Library/Details.cshtml
@model GUS_book.Models.DetailsUserViewModel

@{
    ViewData["Title"] = "Описание пользователя";
}


<div>
    <h2>Информация о пользователе</h2>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        @Html.HiddenFor(model => model.MaxBooks)
    </dl>

    <hr />
</div>
<h2>Книги, прикреплённые к пользователю</h2>
@Html.ValidationSummary(true, "В результате запроса произошла одна или несколько ошибок:", new {@class = "alert-warning" })
<div class="parent">
    @if (Model.Books.Count() == 0)
    {
        <div class="child">
            <text class="alert-info">Список книг пуст</text>
        </div>
    }
    else
    {
        @foreach (var book in Model.Books)
        {
            <div class="child">
                <div>
                    <p class="row col-sm-4"> @Html.DisplayFor(item => book.Author)</p>
                </div>
                <div class="list-group-item-secondary">
                    <p class="row col-sm-4"> @Html.DisplayFor(item => book.Title)</p>
                </div>
                <div>
                    <p class="row col-sm-4"> @Html.DisplayFor(item => book.Year)</p>
                </div>
            </div>
            <hr />
        }
    }
</div>

<div>
    <a id="editLink" class="btn btn-primary" name="editLink" data-ajax="true">Изменить</a>
    <a id="backLink" class="btn btn-link" name="backLink" asp-action="Users">Назад к списку пользователей</a>
</div>

<hr />

<div id="results">

</div>

<div id="loadingDiv" hidden="hidden" class="alert-info">Идёт загрузка...</div>

@section Scripts
{
    <script type="text/javascript">
    $('#editLink').ajaxStart(function () {
        $('#loadingDiv').show();
        });

        $('#editLink').ajaxStop(function () {
        $('#loadingDiv').hide();
        });

        $('#editLink').click(function () {
        $.ajax(
            {
                type: "GET",
                url: '@Url.RouteUrl(new { controller = "Library", action = "BookList", Id = Url.ActionContext.RouteData.Values["Id"], Mb = Model.MaxBooks })',
                async: true,
                cache: false,
                success: function (result) {
                    $("#results").html(result);
                },
                error: function (error) {
                    alert(error);
                }
            });
        });
    </script>
}

GUS_book/Views/Library/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать</h1>
    <p>Тестовое приложение "Книжный магазин"</p>
</div>

GUS_book/Views/Library/Users.cshtml
@model IEnumerable<GUS_book.Models.Library.User>

<h1>Список пользователей</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Описание и редактирование</a>
            </td>
        </tr>
}
    </tbody>
</table>